Virchenko news
vnko1/news-team-project pull request #24
Opened 2023-03-04 16:15 UTC by innekto

2023-03-04 17:22 UTC, vnko1 requested changes

2023-03-04 17:22 UTC, vnko1 commented on src/scripts/FetchNews.js
> +  //приводимо дату до потрібного формату
я б оцю функцію виніс би в CommonFunctions.js , так як вона ніяк не повʼязана з класом, метод createObj. його теж  слід винести в окрему функцію, але це  не критично

2023-03-04 17:22 UTC, vnko1 commented on src/scripts/FetchNews.js
> +  //обрізаємо опис якщо більше 200 символів
тут так само

2023-03-04 17:22 UTC, vnko1 commented on src/scripts/searchNews.js
> +fetchNews.resetData();
зачем 2 в раза вызывать этот метод?

2023-03-04 17:22 UTC, vnko1 commented on src/scripts/searchNews.js
> +    event.preventDefault();
я бы event.preventDefault() поставил бы перед try. хоть он и 1, и в любом случае этот код выполнится

2023-03-04 17:22 UTC, vnko1 commented on src/scripts/searchNews.js
> +      gallery.innerHTML = `
тут надо будет поменять на картинку с макета, когда она у нас появится

2023-03-04 17:22 UTC, vnko1 commented on src/scripts/searchNews.js
> +        <a class="news-card__more" href="${
в <a> обязательно нужно добавить id="${el.id}", он нужен для localestorage

2023-03-04 19:03 UTC, innekto commented on src/scripts/FetchNews.js
> +  //обрізаємо опис якщо більше 200 символів
понял, ща сделаю

2023-03-04 19:04 UTC, innekto commented on src/scripts/searchNews.js
> +      gallery.innerHTML = `
ну конечно

2023-03-05 19:43 UTC, vnko1 commented on src/scripts/searchNews.js
> +        <a class="news-card__more" href="${
не добавил id

2023-03-05 19:43 UTC, vnko1 approved these changes

2023-03-05 19:45 UTC, merged

2023-03-05 20:35 UTC, innekto commented on src/scripts/searchNews.js
> +        <a class="news-card__more" href="${
куда id добавить